### PR TITLE
mac os 'support'

### LINKED ISSUE #3: Installation error
```
rscodeio::install_theme()
Error in 1:bin_ind : argument of length 0
```

In general, it's best to use `seq_len` or `seq_along` to protect against length-0 issues. <s>There's also a chance this isn't an issue from your package but the plugin architecture itself.</s>

Tried installing on macOS Sierra.

<details>
<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 3.4.3 Patched (2017-12-09 r73876)
#>  os       macOS Sierra 10.12.6                       
#>  system   x86_64, darwin15.6.0                       
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_AU.UTF-8                                
#>  ctype    en_AU.UTF-8                                
#>  tz       Australia/Adelaide                         
#>  date     2019-07-08                                 
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version     date       lib
#>  assertthat    0.2.0       2017-04-11 [1]
#>  backports     1.1.2       2017-12-13 [1]
#>  callr         2.0.3       2018-04-16 [1]
#>  cli           1.0.1.9000  2019-01-23 [1]
#>  crayon        1.3.4       2018-12-19 [1]
#>  debugme       1.1.0.9000  2018-04-16 [1]
#>  desc          1.2.0       2018-05-01 [1]
#>  devtools      2.0.2       2019-04-08 [1]
#>  digest        0.6.18      2018-10-10 [1]
#>  evaluate      0.13        2019-02-12 [1]
#>  fs            1.2.6       2018-08-23 [1]
#>  glue          1.3.0       2018-07-17 [1]
#>  highr         0.7         2018-06-09 [1]
#>  htmltools     0.3.6       2017-04-28 [1]
#>  knitr         1.23        2019-05-18 [1]
#>  magrittr      1.5         2014-11-22 [1]
#>  memoise       1.1.0       2017-04-21 [1]
#>  pkgbuild      1.0.2       2018-10-16 [1]
#>  pkgload       1.0.2       2018-10-29 [1]
#>  prettyunits   1.0.2       2015-07-13 [1]
#>  R6            2.3.0       2018-10-04 [1]
#>  Rcpp          1.0.0       2018-11-07 [1]
#>  remotes       2.0.2       2018-10-30 [1]
#>  rlang         0.3.1       2019-01-08 [1]
#>  rmarkdown     1.13        2019-05-22 [1]
#>  rprojroot     1.3-2       2018-01-03 [1]
#>  rscodeio      0.0.1       2019-07-08 [1]
#>  rstudioapi    0.10.0-9000 2019-04-10 [1]
#>  sessioninfo   1.1.1       2018-11-05 [1]
#>  stringi       1.2.4       2018-07-20 [1]
#>  stringr       1.4.0       2019-02-10 [1]
#>  testthat      2.0.1       2018-10-13 [1]
#>  usethis       1.4.0       2018-08-14 [1]
#>  withr         2.1.2       2018-03-15 [1]
#>  xfun          0.7         2019-05-14 [1]
#>  yaml          2.2.0       2018-07-25 [1]
#>  source                                
#>  CRAN (R 3.4.0)                        
#>  CRAN (R 3.4.3)                        
#>  Github (r-lib/callr@2a73c8f)          
#>  Github (r-lib/cli@94e2fc5)            
#>  Github (gaborcsardi/crayon@74bee76)   
#>  Github (gaborcsardi/debugme@f4a116a)  
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.3)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.0)                        
#>  CRAN (R 3.4.3)                        
#>  CRAN (R 3.4.0)                        
#>  CRAN (R 3.4.0)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.0)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.3)                        
#>  CRAN (R 3.4.3)                        
#>  Github (anthonynorth/rscodeio@e601e55)
#>  Github (rstudio/rstudioapi@7038aee)   
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.4)                        
#>  CRAN (R 3.4.3)                        
#>  CRAN (R 3.4.4)                        
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.4/Resources/library
```

</details>

As for the issue itself, I'll see if I can see why it's failing.

### PR DESCRIPTION
**Pull request by MilesMcBain**
Make the QT theme activate/deactivate do nothing on Mac OS. I think this should resolve #3 . Although we'll need a helper to test.

Also added a note about this to Mac section in README.

### CODE REVIEW

**Comment by jonocarroll** [comment]
FYI, still needs to update `get_rstudio_location`.

**Comment by MilesMcBain** [comment]
Ah Right. Thanks Jono 😅👍

**Comment by alistaire47** [comment]
Just tried this branch and it works great on Mojave. 🎉 Thank you all!

**Comment by jonocarroll** [comment]
Installation now works, but I do get the overly spaced line number issue (#7). Great work, though!

**Pull request merged**
